config/routes.rb
Gururs::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :events, only: [:index, :show]
  resources :users, only: [:index]

  resources :authorizations, only: [:destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'content_pages#home'

  get '/about' => 'content_pages#about'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end

  end
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates :provider, :uid, presence: true
  scope :provider, ->(provider) { where(provider: provider).limit(1) }
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :talks

  validates :name, :enroll_url, :happens_at, presence: true

  scope :next, -> { where('happens_at >= ?', DateTime.now).
                    order('happens_at ASC') }
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  validates :title, :event, presence: true
  scope :with_video, -> { where("video_code != ''") }
  scope :with_audio, -> { where("audio_code != ''") }
  scope :without_media, -> { where(video_code: nil, audio_code: nil) }

  def video?
    video_code.present?
  end

  def audio?
    audio_code.present?
  end

  def no_media?
    ! (video? || audio?)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :authorizations, dependent: :destroy
  has_many :talks
  validates :name, presence: true
  validates :admin_time_from, presence: true, if: :admin?

  def member_since
    if admin?
      from = admin_time_from
      to = (admin_time_to.present? ? admin_time_to : "agora")
    else
      from = created_at.year
      to = "agora"
    end
    "De #{from} até #{to}."
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if auth = session[:omniauth]
        user.email = auth.info.email if auth.info.email.present?
        user.name = auth.info.name
        user.image = auth.info.image
        user.github_username = auth.extra.raw_info.login if auth.extra and auth.extra.raw_info
        user.authorizations.build(provider: auth.provider, uid: auth.uid)
      end
    end
  end

  def avatar_url(size = 100)
    return image if image.present?
    host = "http://www.gururs.com"
    default_image = ActionController::Base.helpers.asset_path('default_avatar.png')
    "http://gravatar.com/avatar/#{Digest::MD5.new.update(email)}.jpg?s=#{size}&d=#{host}#{default_image}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,
                                                            :email,
                                                            :github_username,
                                                            :twitter_username,
                                                            :password,
                                                            :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name,
                                                                   :email,
                                                                   :github_username,
                                                                   :twitter_username,
                                                                   :password,
                                                                   :current_password,
                                                                   :password_confirmation) }
  end

  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  before_filter :authenticate_user!

  inherit_resources
  actions :destroy
  def destroy
    destroy! do |format|
      format.html { redirect_to edit_user_registration_url }
    end
  end
end

app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  def home
    @events      = Event.next.limit(3)
    @video_talks = Talk.with_video.last(3)
  end

  def about
    @managers = User.where("admin = ? AND admin_time_to IS NULL ", true)
    @ex_managers = User.where("admin = ? AND admin_time_to IS NOT NULL ", true)
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  actions :index, :show

  protected

  def collection
    @events ||= end_of_association_chain.order('happens_at DESC')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events      = Event.next.limit(3)
    @video_talks = Talk.with_video.last(3)
  end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    omniauth = env['omniauth.auth']
    if user_signed_in?
      current_user.authorizations.where(provider: omniauth['provider'],
                                        uid:      omniauth['uid']).first_or_create
      redirect_to root_path, notice: I18n.t('devise.omniauth_callbacks.success', kind: omniauth['provider'])
    else
      authorization = Authorization.where(provider: omniauth['provider'],
                                          uid:      omniauth['uid']).first
      if authorization
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: omniauth['provider'])
        sign_in_and_redirect(authorization.user, event: :authentication)
      else
        session[:omniauth] = omniauth
        redirect_to new_user_registration_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :index
end

app/helpers/application_helper.rb
module ApplicationHelper
  def video_thumb_image(entity_with_video)
    image_tag("http://img.youtube.com/vi/#{entity_with_video.video_code}/0.jpg")
  end

  def video_thumb(entity_with_video)
    content_tag('iframe', nil, width:           '300',
                               height:          '225',
                               frameborder:     '0',
                               allowfullscreen: true,
                               src:             "https://www.youtube.com/embed/#{entity_with_video.video_code}")
  end

  def audio_thumb(entity_with_audio)
    content_tag('iframe', nil, width:           '940',
                               height:          '160',
                               frameborder:     'no',
                               src:             "https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%#{entity_with_audio.audio_code}")
  end
end

app/views/content_pages/about.html.slim
.container
  h1 Sobre o grupo

  p Este é o Grupo de Usuários Ruby do Rio Grande do Sul. Nosso objetivo com ele é acima de tudo reunir pessoas interessadas em discutir boas práticas, trocar experiências e adquirir novas, independente do nível de conhecimento de cada um.
  p Nos nossos encontros você não vai ouvir apenas sobre Ruby. Obviamente este será um assunto constante na maioria das discussões, que tem como função principal incentivar argumentações e aprender sobre as melhores abordagens para cada tipo de problema.
  p Se você se sentir à vontade para propor assuntos novos (ou antigos) para abordagem, sugestões em eventos ou contribuições de qualquer tipo, estaremos sempre abertos. Falar com um dos organizadores é apenas uma das formas de fazê-lo, já que acreditamos que o grupo é feito pelo conjunto dos usuários de Ruby da região.

  br/
  - if @managers.any?
    h2 Mantenedores
    = render @managers

  div.ex_maintainers
  - if @ex_managers.any?
    h2 Ex-Mantenedores
    = render @ex_managers

app/views/content_pages/home.html.slim
section.events
  .container
    h1.title Próximos Eventos
    a[name="events"]
    = render @events

section.videos
  .container
    h1.title Últimos vídeos
    - @video_talks.each do |talk|
      .span4.box-video
        = link_to video_thumb_image(talk), talk.event
        h2 = link_to talk.title, talk.event
        - if talk.user
          p.name
            = talk.user.name

app/views/events/_event.html.slim
.events
  h2
    = link_to event.name, event
    span.pull-right = l event.happens_at, format: :long

app/views/events/index.html.slim
section.events
  .container
    h1.title Todos os eventos
    = render @events

app/views/events/show.html.slim
section.content-highlighted
  .container
    h1.title
      = resource.name
      small
        | &nbsp;
        = l resource.happens_at, format: :long

    .highlighted-inverse
      - if resource.enroll_url.present?
        = link_to t('.enroll_button'), resource.enroll_url, class: 'btn-enroll btn btn-large'

      - if resource.proposals_url.present?
        = link_to t('.proposals_button'), resource.proposals_url, class: 'btn-proposals btn btn-large pull-right'

- if resource.talks.with_video.any?
  section.videos
    .container
      h1.title Vídeos
      = render resource.talks.with_video, { embed: true }

- if resource.talks.with_audio.any?
  section.audios
    .container
      h1.title Áudios
      = render resource.talks.with_audio

- if resource.talks.without_media.any?
  section.videos
    .container
      h1.title Não gravados
      = render resource.talks.without_media

app/views/home/index.html.slim
.row
  .span8
    = render @events

.row
  - @video_talks.each do |talk|
    .span3
      = link_to video_thumb_image(talk), talk.event
      strong = link_to talk.title, talk.event

app/views/layouts/_flash.html.slim
.flash
  - for key, message in flash
    - key = '' if key == 'alert'
    div class="#{key}"
      = message

app/views/layouts/_footer.html.slim
footer

app/views/layouts/_header.html.slim
header
  .navbar.navbar-static-top.navbar-inverse
    .navbar-inner
      .container
        .nav-collapse.collapse
          ul.nav.secondary-nav
            li= link_to 'Sobre o grupo', about_path
            li= link_to 'Eventos', events_path
            li= link_to 'Membros', users_path
            li= link_to 'Lista', 'https://groups.google.com/forum/#!forum/guru-rs', target: :blank
          ul.nav.secondary-nav.pull-right
            li= link_to 'Entrar', new_user_session_path unless user_signed_in?
            li= link_to 'Me cadastrar', new_user_registration_path unless user_signed_in?
          - if user_signed_in?
            ul.nav.pull-right
              li.dropdown
                a.dropdown-toggle href="#" data-toggle="dropdown"
                  = image_tag current_user.avatar_url(20), width: 20
                  | &nbsp;
                  = current_user.name
                  b.caret
                ul.dropdown-menu
                  li= link_to 'Configurações', edit_user_registration_path
                  - if user_signed_in? && current_user.admin?
                    li= link_to 'Admin', "/admin", data: { :'no-turbolink' => true }
                  li= link_to 'Sair', destroy_user_session_path, method: :delete if user_signed_in?

  - if controller.controller_name == 'content_pages' and controller.action_name == 'home'
    section.home-highlight.highlight-image[data-url=image_path('home-highlight.jpg')]
      .container
        .row
          .span6
            = link_to 'GURU-RS', root_path, class: 'logo'
          .span8
            h1 Este é o Grupo de Usuários Ruby do Rio Grande do Sul
            - if @events.any?
              a.btn.btn-large.btn-next-event href="#events"
                | Próximo evento
                span = l @events.first.happens_at, format: :short
  - else
    section.highlight.highlight-image[data-url=image_path('highlight.jpg')]
      .container
        = link_to 'GURU-RS', root_path, class: 'logo'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = page_title app_name: "GURU-RS - Grupo de Usuários Ruby do Rio Grande do Sul"
    = stylesheet_link_tag "application"
    meta[charset="utf-8"]
    = yield(:meta_tags)
    = csrf_meta_tag
    = javascript_include_tag "application"
  body
    = initjs_tag app_name: "Gururs"
    = render 'layouts/flash', flash: flash if flash.present?
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/talks/_talk.html.slim
- if talk.video?
  .span4.box-video
    - if defined?(embed)
      = video_thumb(talk)
    - else
      = link_to video_thumb_image(talk), talk.event

    - if defined?(embed)
      h2 = talk.title
    - else
      h2 = link_to talk.title, talk.event
    - if talk.user
      p
        = t('keywords.by')
        |  #{talk.user.name}
- elsif talk.audio?
  .box-audio
    = audio_thumb(talk)
    h2 = talk.title
    - if talk.user
      p
        = t('keywords.by')
        |  #{talk.user.name}
- elsif talk.no_media?
    h2 = talk.title
    - if talk.user
      p
        = t('keywords.by')
        |  #{talk.user.name}

app/views/users/_user.html.slim
.user-box.span3
  .avatar
    = image_tag user.avatar_url, size: '100x100'
  .name
    strong = user.name
  .admin_time
    = user.member_since
  - if user.github_username.present?
    = link_to user.github_username, "http://github.com/#{user.github_username}", class: 'github-icon'
  - if user.twitter_username.present?
    = link_to user.twitter_username, "http://twitter.com/#{user.twitter_username}", class: 'twitter-icon'

app/views/users/index.html.slim
.container
  h1 Membros

  .row
    = render @users